DROP TABLE CART_ITEM IF EXISTS;
DROP TABLE CART IF EXISTS;
DROP TABLE PRODUCTS IF EXISTS;
DROP TABLE CUSTOMERS IF EXISTS;

CREATE TABLE PRODUCTS
(
  ID             VARCHAR(16) PRIMARY KEY,
  NAME           VARCHAR(50),
  DESCRIPTION    VARCHAR(250),
  UNIT_PRICE     DECIMAL,
  MANUFACTURER   VARCHAR(50),
  CATEGORY       VARCHAR(50),
  CONDITION      VARCHAR(50),
  UNITS_IN_STOCK BIGINT,
  UNITS_IN_ORDER BIGINT,
  DISCONTINUED   BOOLEAN
);

CREATE TABLE CUSTOMERS
(
  ID          VARCHAR(16) PRIMARY KEY,
  NAME        VARCHAR(50),
  ADDRESS     VARCHAR(250),
  ORDERS_MADE BIGINT
);

CREATE TABLE CART
(
  ID VARCHAR(32) PRIMARY KEY -- SESSION_ID length for Tomcat is 16 bytes (or 32 symbols)
);

CREATE TABLE CART_ITEM
(
  ID         VARCHAR(50),
  PRODUCT_ID VARCHAR(16) FOREIGN KEY REFERENCES PRODUCTS (ID),
  CART_ID    VARCHAR(32) FOREIGN KEY REFERENCES CART (ID),
  QUANTITY   BIGINT,
  CONSTRAINT CART_ITEM_PK PRIMARY KEY (ID, CART_ID)
);